version: "3.1"

services:
  db:
    build: .
    container_name: castor
    restart: always
    ports:
      - "5437:5432"
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=prisma-nest

  dbtest:
    build: .
    container_name: castor-teste
    restart: always
    ports:
      - "5436:5432"
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=prisma-nest
